version: "3.8"

services:
  db:
    image: postgres:15
    container_name: olist_warehouse
    environment:
      POSTGRES_USER: caelan_admin
      POSTGRES_PASSWORD: password_rahasia
      POSTGRES_DB: olist_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U caelan_admin -d olist_db"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
